#!/usr/bin/env bash
# This script redirects a page

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo chmod -R 755 /var/www
sudo service nginx stop
new_config="server_name \_\;\n\tlocation \/redirect_me \{\n\t\treturn 301 \$scheme\:\/\/\$http_host\;\n\t\}\n"
sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx start
