#!/usr/bin/env bash
# Redirect a page not found
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo chmod -R 755 /var/www
sudo service nginx stop
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404-html.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404-html.html;
   location = /404-html.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx start
