#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
apt-get -y update
sudo apt-get install haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 54.236.24.140:80 check
        server web2 35.174.204.206:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
