#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
apt-get -y update
sudo apt-get install haproxy=2.7.\*

# Listen to web1 and web2 servers
echo "frontend main
        bind *:80
        mode http
        default_backend servers

backend web-backend
        balance roundrobin
        server web1 54.160.113.91:80 check
        server web2 3.84.158.64:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
