#!/usr/bin/bash
#Installs ufw and set rules

sudo apt update && sudo upgrade -y
sudo apt install ufw
sudo ufw deny incoming -y
sudo ufw allow in 22/tcp
sudo ufw allow in 443/tcp
sudo ufw allow in 80/tcp
yes | sudo ufw enable

