#!/usr/bin/env bash
# Runs nginx as the user nginx and listening on port 8080 but shorter
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
